
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv-0
  labels:
    type: local
spec:
  capacity: 
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/registry
  claimRef:
    namespace: registry
    name: registry-registry-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-node