apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o ./.helm/templates
    kompose.controller.type: statefulset
    kompose.service.expose: {{ .Values.host }}
    kompose.service.expose.ingress-class-name: nginx
    kompose.version: 1.28.0 (HEAD)
    kompose.volume.size: 15Gi
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  creationTimestamp: null
  labels:
    io.kompose.service: registry
  name: registry
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              service:
                name: registry
                port:
                  number: 80
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
